### ISSUE TITLE
TODO: Fix missing cpp rewrites

### ISSUE THREAD

**Issue by CommanderRedYT** [bobbycar-graz/bobbycar-boardcomputer-firmware#132]
ToDo list for .h / .cpp files that need refactoring

## Files without .cpp file
- [x] main/buildserver.h

## Files with empty .cpp file
- [x] main/texts.cpp
- [ ] main/settingsutils.cpp
- [ ] main/changevaluedisplay_bluetoothmode.cpp
- [ ] main/modeinterface.cpp
- [ ] main/dpad5wire.cpp
- [ ] main/ledstripdefines.cpp
- [ ] main/esptexthelpers.cpp
- [ ] main/changevaluedisplay_controlmode.cpp
- [ ] main/debugcolorhelpers.cpp
- [ ] main/changevaluedisplay_wifi_power_t.cpp
- [ ] main/displays/dpad6wiredebugdisplay.cpp
- [ ] main/displays/gametrakcalibratedisplay.cpp
- [ ] main/displays/dpad5wiredebugdisplay.cpp
- [ ] main/displays/dpad5wire2outdebugdisplay.cpp
- [ ] main/displays/bmsdisplay.cpp
- [x] main/displays/menus/timersmenu.cpp
- [x] main/displays/menus/presetsmenu.cpp
- [x] main/displays/menus/selectotabuildmenu.cpp
- [x] main/displays/menus/wifiscanmenu.cpp
- [ ] main/displays/menus/genericwifisettingsmenu.cpp
- [ ] main/displays/menus/ledstripselectblinkmenu.cpp
- [x] main/displays/menus/crashmenu.cpp
- [ ] main/displays/menus/motorfeedbackdebugmenu.cpp
- [ ] main/displays/menus/profilesmenu.cpp
- [ ] main/displays/menus/accesspointwifisettingsmenu.cpp
- [ ] main/displays/menus/mosfetsmenu.cpp
- [ ] main/displays/menus/motorstatedebugmenu.cpp
- [ ] main/displays/menus/ledstripselectotamode.cpp
- [x] main/displays/menus/enablemenu.cpp
- [ ] main/displays/menus/dynamicdebugmenu.cpp
- [ ] main/displays/menus/commanddebugmenu.cpp
- [x] main/displays/menus/invertmenu.cpp
- [ ] main/displays/menus/ledstripselectanimationmenu.cpp
- [ ] main/displays/menus/gametrakmodesettingsmenu.cpp
- [x] main/displays/menus/bmsmenu.cpp
- [ ] main/displays/menus/feedbackdebugmenu.cpp
- [ ] main/displays/menus/blesettingsmenu.cpp
- [ ] main/statustexthelper.cpp
- [ ] main/dpad3wire.cpp
- [ ] main/actions/erasenvsaction.cpp
- [ ] main/actions/loadsettingsaction.cpp
- [ ] main/actions/ledstripanimationactions.cpp
- [ ] main/actions/bmsturnonchargeaction.cpp
- [ ] main/actions/bluetoothflushaction.cpp
- [ ] main/actions/bmsturnoffdischargeaction.cpp
- [ ] main/actions/bluetoothconnectbmsaction.cpp
- [ ] main/actions/bluetoothdisconnectaction.cpp
- [ ] main/actions/switchprofileaction.cpp
- [ ] main/actions/ledstripblinkactions.cpp
- [ ] main/actions/updateswapfrontbackaction.cpp
- [ ] main/actions/modesettingsaction.cpp
- [ ] main/actions/tempomatmodeapplycurrentpeedaction.cpp
- [ ] main/actions/bmsturnondischargeaction.cpp
- [ ] main/actions/bluetoothbeginmasteraction.cpp
- [ ] main/actions/wifiscanaction.cpp
- [ ] main/actions/bmsturnoffchargeaction.cpp
- [ ] main/actions/savesettingsaction.cpp
- [ ] main/actions/bluetoothendaction.cpp
- [ ] main/actions/multiaction.cpp
- [ ] main/changevaluedisplay_larsmmode_mode.cpp
- [ ] main/stringsettings.cpp
- [ ] main/dpad5wire_2out.cpp
- [ ] main/changevaluedisplay_controltype.cpp
- [ ] main/debugtexthelpers.cpp
- [ ] main/feedbackparser.cpp
- [ ] main/rotary.cpp
- [ ] main/dpad.cpp
- [ ] main/bluetoothmode.cpp
- [ ] main/settings.cpp
- [ ] main/bmsutils.cpp
- [ ] main/dpad6wire.cpp
- [ ] main/macros_bobbycar.cpp
- [ ] main/changevaluedisplay_wifi_mode_t.cpp
- [ ] main/bluetoothtexthelpers.cpp
- [ ] main/types.cpp
- [ ] main/bletexthelpers.cpp

**Comment by CommanderRedYT** [comment]
Note: main/displays/menus/bluetoothsettingsmenu.h cannot be refactored because "BluetoothSerial.h" is missing.
